---
# handlers file

- name: restart node_exporter
  ansible.builtin.systemd_service:
    name: prometheus_node_exporter.service
    state: restarted
  when: prometheus_node_exporter_service_started | bool