---

# defaults file

prometheus_system_user_name: prometheus

prometheus_node_exporter_installation_path: /var/lib/prometheus
prometheus_node_exporter_binary_name: node_exporter

prometheus_node_exporter_service_enabled: true
prometheus_node_exporter_service_started: true

prometheus_node_exporter_os: linux
prometheus_node_exporter_arch: amd64
prometheus_node_exporter_version: 1.8.1
prometheus_node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.{{ prometheus_node_exporter_os }}-{{ prometheus_node_exporter_arch }}.tar.gz"

prometheus_node_exporter_extra_args: "" # Example: "--web.listen-address=:9200"

prometheus_node_exporter_collector_enabled: []
  # - cpu_vulnerabilities

prometheus_node_exporter_collector_disabled: []
  # - bcache
  # - fibrechannel
  # - hwmon
  # - mdadm
  # - nvme
  # - powersupplyclass
  # - selinux